<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PersonnelSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('personnels')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = now();

        DB::table('personnels')->insert([
            ['personnel_id' => 1,   'first_name' => 'ATTY. JAYFRANCIS',   'middle_name' => 'D.',  'last_name' => 'BAGO',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 2,   'first_name' => 'Danilo',             'middle_name' => 'A.',  'last_name' => 'Paraguya',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 3,   'first_name' => 'Carla Niña',         'middle_name' => 'S.',  'last_name' => 'Salomon',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 4,   'first_name' => 'Elensita',           'middle_name' => 'V.',  'last_name' => 'Piit',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 5,   'first_name' => 'Karen',              'middle_name' => 'I.',  'last_name' => 'Barangot',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 6,   'first_name' => 'Noelene Joy',        'middle_name' => 'B.',  'last_name' => 'Jadumas',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 7,   'first_name' => 'Ray Amor',           'middle_name' => 'L.',  'last_name' => 'Arce',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 8,   'first_name' => 'Monico',             'middle_name' => 'B.',  'last_name' => 'Burgos',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 9,   'first_name' => 'Helen',              'middle_name' => 'A.',  'last_name' => 'Baquiro',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 10,  'first_name' => 'Aaron',              'middle_name' => 'M.',  'last_name' => 'Vacalares',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 11,  'first_name' => 'JOSEPH',             'middle_name' => 'A.',  'last_name' => 'ACTUB',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 12,  'first_name' => 'MAISIE',             'middle_name' => 'M.',  'last_name' => 'QUIDELLA',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 13,  'first_name' => 'Rezan',              'middle_name' => 'M.',  'last_name' => 'Cagatan',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 14,  'first_name' => 'Trishia Dominique',  'middle_name' => 'Z.',  'last_name' => 'Pitogo',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 15,  'first_name' => 'CHERRYL',            'middle_name' => 'G.',  'last_name' => 'MAGNETICO',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 16,  'first_name' => 'Gerald Kim',         'middle_name' => 'U.',  'last_name' => 'Garcia',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 17,  'first_name' => 'Rene',               'middle_name' => 'D.',  'last_name' => 'Magboo',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 18,  'first_name' => 'ENGR. ROMEL',        'middle_name' => 'C.',  'last_name' => 'LONOY REE',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 19,  'first_name' => 'Maebel Lou',         'middle_name' => 'A.',  'last_name' => 'Tedlos',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 20,  'first_name' => 'Daisy Mar',          'middle_name' => 'Q.',  'last_name' => 'Autida',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 21,  'first_name' => 'Efren',              'middle_name' => 'A.',  'last_name' => 'Daayata Jr.',        'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 22,  'first_name' => 'Edsil',              'middle_name' => 'V.',  'last_name' => 'Saarenas',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 23,  'first_name' => 'Leonardo',           'middle_name' => 'M.',  'last_name' => 'Cagalawan',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 24,  'first_name' => 'Dionisio',           'middle_name' => 'G.',  'last_name' => 'Montemayor III',     'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 25,  'first_name' => 'Odette',             'middle_name' => 'P.',  'last_name' => 'Galangke',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 26,  'first_name' => 'CANDIDO',            'middle_name' => 'M.',  'last_name' => 'DALIGDIG JR.',       'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 27,  'first_name' => 'DANILO',             'middle_name' => 'E.',  'last_name' => 'DAROY JR.',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 28,  'first_name' => 'Clessa Monique',     'middle_name' => 'O.',  'last_name' => 'Garces',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 29,  'first_name' => 'Rhally Mae',         'middle_name' => 'G.',  'last_name' => 'Piit',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 30,  'first_name' => 'Chizarina',          'middle_name' => 'M.',  'last_name' => 'Ortigoza',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 31,  'first_name' => 'Neal Oliver',        'middle_name' => 'H.',  'last_name' => 'Actub',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 32,  'first_name' => 'Eliezer',            'middle_name' => 'A.',  'last_name' => 'Vacalares Jr',       'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 33,  'first_name' => 'Hermito',            'middle_name' => 'B.',  'last_name' => 'Laid Jr.',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 34,  'first_name' => 'Palmero',            'middle_name' => 'F.',  'last_name' => 'Ebonia',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 35,  'first_name' => 'Ana Karla',          'middle_name' => 'L.',  'last_name' => 'Cabrera',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 36,  'first_name' => 'Nestor',             'middle_name' => 'M.',  'last_name' => 'Sapio III',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 37,  'first_name' => 'Jeric John',         'middle_name' => 'P.',  'last_name' => 'Cagalawan',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 38,  'first_name' => 'Jeffrey',            'middle_name' => 'P.',  'last_name' => 'Puasan',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 39,  'first_name' => 'JOMAR FRANCO',       'middle_name' => 'D.',  'last_name' => 'BAGO',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 40,  'first_name' => 'Rhodelyn Mae',       'middle_name' => 'B.',  'last_name' => 'Roa',                'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 41,  'first_name' => 'Lani',               'middle_name' => 'Y.',  'last_name' => 'Lagra',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 42,  'first_name' => 'Ariel',              'middle_name' => 'V.',  'last_name' => 'Nob',                'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 43,  'first_name' => 'Jeford',             'middle_name' => 'P.',  'last_name' => 'Pastrana',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 44,  'first_name' => 'xxxxxxxxxxx',        'middle_name' => 'S.',  'last_name' => 'xxxxxxxx',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 45,  'first_name' => 'Enrico',             'middle_name' => null,  'last_name' => 'Fornoles',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 46,  'first_name' => 'Arcelie',            'middle_name' => 'C.',  'last_name' => 'Yasay',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 47,  'first_name' => 'Greg Ulysses',       'middle_name' => 'T.',  'last_name' => 'Obsioma',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 48,  'first_name' => 'ENGR. ROLAND',       'middle_name' => 'B.',  'last_name' => 'CAINHOG',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 49,  'first_name' => 'Edgar',              'middle_name' => 'C.',  'last_name' => 'Cariliman',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 50,  'first_name' => 'GREG',               'middle_name' => 'M.',  'last_name' => 'RADAZA MBA',         'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 51,  'first_name' => 'Maria Fe',           'middle_name' => 'O.',  'last_name' => 'Tampus',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 52,  'first_name' => 'Ralph',              'middle_name' => null,  'last_name' => 'Basalo',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 53,  'first_name' => 'Armando',            'middle_name' => 'E.',  'last_name' => 'Yana',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 54,  'first_name' => 'HILAIRE MAY',        'middle_name' => 'F.',  'last_name' => 'BACULIO CPA',        'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 55,  'first_name' => 'Jonathan',           'middle_name' => 'L.',  'last_name' => 'Loreno',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 56,  'first_name' => 'Ma. Jessiel',        'middle_name' => 'L.',  'last_name' => 'Gutierrez',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 57,  'first_name' => 'Ruby',               'middle_name' => 'C.',  'last_name' => 'Mangubat',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 58,  'first_name' => 'Shaira Joyce',       'middle_name' => 'P.',  'last_name' => 'Edera',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 59,  'first_name' => 'Cecilia',            'middle_name' => 'A.',  'last_name' => 'Actub',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 60,  'first_name' => 'LALAINE',            'middle_name' => 'M.',  'last_name' => 'CARILIMAN',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 61,  'first_name' => 'Enn Meriell',        'middle_name' => 'L.',  'last_name' => 'Largo',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 62,  'first_name' => 'Ruel',               'middle_name' => 'Y.',  'last_name' => 'Gamolo',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 63,  'first_name' => 'Jean',               'middle_name' => 'L.',  'last_name' => 'Bacadon',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 64,  'first_name' => 'Daisy Mae',          'middle_name' => 'A.',  'last_name' => 'Abellanosa',         'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 65,  'first_name' => 'Cherrelyn',          'middle_name' => 'C.',  'last_name' => 'Aba',                'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 66,  'first_name' => 'Danilo',             'middle_name' => 'G.',  'last_name' => 'Yana Jr.',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 67,  'first_name' => 'Ed Paulo',           'middle_name' => 'N.',  'last_name' => 'Estrada',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 68,  'first_name' => 'Fe',                 'middle_name' => 'Y.',  'last_name' => 'Naalatan',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 69,  'first_name' => 'Niño Jose',          'middle_name' => 'B.',  'last_name' => 'Macasarte',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 70,  'first_name' => 'Adiodeta',           'middle_name' => 'B.',  'last_name' => 'Malaya',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 71,  'first_name' => 'Kim',                'middle_name' => 'S.',  'last_name' => 'Lazo',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 72,  'first_name' => 'EDGAR',              'middle_name' => 'C.',  'last_name' => 'OLACO REA REB',      'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 73,  'first_name' => 'Rosalie',            'middle_name' => 'E.',  'last_name' => 'Buna',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 74,  'first_name' => 'Nick',               'middle_name' => 'O.',  'last_name' => 'Illana',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 75,  'first_name' => 'Joel',               'middle_name' => 'A.',  'last_name' => 'Piit',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 76,  'first_name' => 'Mae Glaiza',         'middle_name' => 'T.',  'last_name' => 'Paclar',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 77,  'first_name' => 'Fatima Anne',        'middle_name' => 'S.',  'last_name' => 'Pagador',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 78,  'first_name' => 'Arnel',              'middle_name' => 'M.',  'last_name' => 'Apdohan',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 79,  'first_name' => 'Eva',                'middle_name' => 'R.',  'last_name' => 'Togonon',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 80,  'first_name' => 'Reno',               'middle_name' => 'D.',  'last_name' => 'German',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 81,  'first_name' => 'EMILY GRACE',        'middle_name' => 'G.',  'last_name' => 'BANAL',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 82,  'first_name' => 'Jovie',              'middle_name' => null,  'last_name' => 'Sabellina',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 83,  'first_name' => 'Glenn',              'middle_name' => 'D.',  'last_name' => 'Aracena',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 84,  'first_name' => 'Deanne Ritz',        'middle_name' => 'L.',  'last_name' => 'Carupo',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 85,  'first_name' => 'Mark Louise',        'middle_name' => 'L.',  'last_name' => 'Maleriado',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 86,  'first_name' => 'Leonila',            'middle_name' => 'B.',  'last_name' => 'Dablio',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 87,  'first_name' => 'Ma. Teresa',         'middle_name' => 'L.',  'last_name' => 'Padero',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 88,  'first_name' => 'Marivic',            'middle_name' => 'E.',  'last_name' => 'Añora',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 89,  'first_name' => 'Angelita',           'middle_name' => 'Y.',  'last_name' => 'Malinao',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 90,  'first_name' => 'Aira Coleen',        'middle_name' => null,  'last_name' => 'Muring',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 91,  'first_name' => 'Nadine',             'middle_name' => 'M.',  'last_name' => 'Ebarat',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 92,  'first_name' => 'Hannah',             'middle_name' => 'S.',  'last_name' => 'Licawat',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 93,  'first_name' => 'Janeth',             'middle_name' => 'R.',  'last_name' => 'Tan-gan',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 94,  'first_name' => 'Mae',                'middle_name' => 'M.',  'last_name' => 'Cervantes',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 95,  'first_name' => 'Hazel',              'middle_name' => 'T.',  'last_name' => 'Villiones',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 96,  'first_name' => 'Jennifer',           'middle_name' => null,  'last_name' => 'Fabricante',         'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 97,  'first_name' => 'Hazel',              'middle_name' => 'A.',  'last_name' => 'Bombeo',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 98,  'first_name' => 'Lanny',              'middle_name' => 'L.',  'last_name' => 'Realista',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 99,  'first_name' => 'Joy',                'middle_name' => 'S.',  'last_name' => 'Cosep',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 100, 'first_name' => 'Rejan Mae',          'middle_name' => 'R.',  'last_name' => 'Tan-gan',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 101, 'first_name' => 'Antonio',            'middle_name' => 'M.',  'last_name' => 'Abesamis',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 102, 'first_name' => 'Jomar',              'middle_name' => 'E.',  'last_name' => 'Madronal',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 103, 'first_name' => 'Micy',               'middle_name' => 'C.',  'last_name' => 'Yañez',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 104, 'first_name' => 'Rene',               'middle_name' => 'J.',  'last_name' => 'Barangot',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 105, 'first_name' => 'Aissa',              'middle_name' => 'R.',  'last_name' => 'Orog',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 106, 'first_name' => 'Glenda',             'middle_name' => 'D.',  'last_name' => 'Babatido',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 107, 'first_name' => 'MALYN',              'middle_name' => 'L.',  'last_name' => 'SARMIENTO RSW',      'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 108, 'first_name' => 'Liberty',            'middle_name' => 'L.',  'last_name' => 'Pabilona',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 109, 'first_name' => 'KATHLEEN MAE',       'middle_name' => 'L.',  'last_name' => 'ABORDO',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 110, 'first_name' => 'Marcia Erra',        'middle_name' => 'O.',  'last_name' => 'Balansag',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 111, 'first_name' => 'Dedith',             'middle_name' => 'G.',  'last_name' => 'Mabao',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 112, 'first_name' => 'Chyrel',             'middle_name' => 'B.',  'last_name' => 'Racines',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 113, 'first_name' => 'EDDIE',              'middle_name' => 'C.',  'last_name' => 'MAAPE JR.',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 114, 'first_name' => 'Mailyn',             'middle_name' => 'C.',  'last_name' => 'Quiblat',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 115, 'first_name' => 'John Paul Ceasar',   'middle_name' => 'L.',  'last_name' => 'Lacandula',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 116, 'first_name' => 'Calvin',             'middle_name' => 'A.',  'last_name' => 'Arevalo Jr.',        'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 117, 'first_name' => 'Kriza Gay',          'middle_name' => 'O.',  'last_name' => 'Obradas',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 118, 'first_name' => 'Benjamin',           'middle_name' => 'D.',  'last_name' => 'Macadenden III',     'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 119, 'first_name' => 'Bimbo',              'middle_name' => 'C.',  'last_name' => 'Legaspi',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 120, 'first_name' => 'Vincent Jay',        'middle_name' => null,  'last_name' => 'Enriquez',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 121, 'first_name' => 'Cindy',              'middle_name' => 'M.',  'last_name' => 'Quimanhan',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 122, 'first_name' => 'Julito',             'middle_name' => 'M.',  'last_name' => 'Quiblat',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 123, 'first_name' => 'ENGR. LILIBETH',     'middle_name' => 'S.',  'last_name' => 'UY',                 'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 124, 'first_name' => 'Patrick',            'middle_name' => 'D.',  'last_name' => 'Opeña',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 125, 'first_name' => 'Jefrey',             'middle_name' => 'V.',  'last_name' => 'Pakino',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 126, 'first_name' => 'Charlie',            'middle_name' => 'Q.',  'last_name' => 'Igloria Jr.',        'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 127, 'first_name' => 'Edsyll',             'middle_name' => 'M.',  'last_name' => 'Esmeralda',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 128, 'first_name' => 'Bryle',              'middle_name' => 'C.',  'last_name' => 'Opena',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 129, 'first_name' => 'Michael',            'middle_name' => 'C.',  'last_name' => 'Doydora',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 130, 'first_name' => 'Bernie',             'middle_name' => 'C.',  'last_name' => 'Vacalares',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 131, 'first_name' => 'Bernard',            'middle_name' => 'L.',  'last_name' => 'Paclar',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 132, 'first_name' => 'Apollo',             'middle_name' => 'E.',  'last_name' => 'Madelo',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 133, 'first_name' => 'Florence Sheila',    'middle_name' => 'M.',  'last_name' => 'Jacalan',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 134, 'first_name' => 'Melbin',             'middle_name' => 'B.',  'last_name' => 'Bulaso',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 135, 'first_name' => 'Edgar',              'middle_name' => 'D.',  'last_name' => 'Rago',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 136, 'first_name' => 'Gonzalo',            'middle_name' => 'A.',  'last_name' => 'Anteporta',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 137, 'first_name' => 'Vifred',             'middle_name' => 'C.',  'last_name' => 'Cagalawan',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 138, 'first_name' => 'Rey',                'middle_name' => 'L.',  'last_name' => 'Baculio',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 139, 'first_name' => 'Edsel',              'middle_name' => 'S.',  'last_name' => 'Igloria',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 140, 'first_name' => 'Ceasar',             'middle_name' => 'G.',  'last_name' => 'Lacandula',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 141, 'first_name' => 'Michael',            'middle_name' => 'E.',  'last_name' => 'Escaba',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 142, 'first_name' => 'Kenneth John',       'middle_name' => 'L.',  'last_name' => 'Padero',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 143, 'first_name' => 'Alfred',             'middle_name' => 'C.',  'last_name' => 'Galdo',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 144, 'first_name' => 'ENGR. JESON',        'middle_name' => 'G.',  'last_name' => 'JACALAN',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 145, 'first_name' => 'Lester',             'middle_name' => 'L.',  'last_name' => 'Boter',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 146, 'first_name' => 'ENGR. RANDOLPH',     'middle_name' => 'Q.',  'last_name' => 'HALLASGO',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 147, 'first_name' => 'Loelle Joseph',      'middle_name' => 'D.',  'last_name' => 'Pacana',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 148, 'first_name' => 'Elbert',             'middle_name' => 'A.',  'last_name' => 'Yasay',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 149, 'first_name' => 'Daisy',              'middle_name' => 'B.',  'last_name' => 'Almazan',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 150, 'first_name' => 'Ulysses Sosa',       'middle_name' => null,  'last_name' => 'Palomares',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 151, 'first_name' => 'DR. JANESSA',        'middle_name' => 'P.',  'last_name' => 'BEARNEZA',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 152, 'first_name' => 'ARIEL BRIAN',        'middle_name' => 'Y.',  'last_name' => 'ORTIGOZA',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 153, 'first_name' => 'Jailyne Jane',       'middle_name' => 'G.',  'last_name' => 'Cartagena',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 154, 'first_name' => 'ETHEL RAE',          'middle_name' => 'C.',  'last_name' => 'REYES',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 155, 'first_name' => 'Shirley',            'middle_name' => 'C.',  'last_name' => 'Centillas',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 156, 'first_name' => 'James Bryan',        'middle_name' => 'Q.',  'last_name' => 'Dunque',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 157, 'first_name' => 'Jonathan',           'middle_name' => 'I.',  'last_name' => 'Dablio',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 158, 'first_name' => 'Melchora',           'middle_name' => 'G.',  'last_name' => 'Hanoyan',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 159, 'first_name' => 'Oliver',             'middle_name' => null,  'last_name' => 'Baculina',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 160, 'first_name' => 'RINA',               'middle_name' => 'A.',  'last_name' => 'CALIZA',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 161, 'first_name' => 'Daniel',             'middle_name' => 'O.',  'last_name' => 'Mag-away',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 162, 'first_name' => 'Rex Ali',            'middle_name' => 'G.',  'last_name' => 'Janubas',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 163, 'first_name' => 'Joefel',             'middle_name' => 'P.',  'last_name' => 'Lagutin',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 164, 'first_name' => 'RYAN',               'middle_name' => 'Y.',  'last_name' => 'DALAGUIADO',         'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 165, 'first_name' => 'Dolorita',           'middle_name' => 'N.',  'last_name' => 'Arao',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 166, 'first_name' => 'Alma',               'middle_name' => 'T.',  'last_name' => 'Gurrea',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 167, 'first_name' => 'Ron Jake',           'middle_name' => 'I.',  'last_name' => 'Romero',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 168, 'first_name' => 'DR. NIELSON',        'middle_name' => 'D.',  'last_name' => 'BATION',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 169, 'first_name' => 'Sophomore',          'middle_name' => 'T.',  'last_name' => 'Vacalares',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 170, 'first_name' => 'Ruben',              'middle_name' => 'B.',  'last_name' => 'Madriaga',           'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 171, 'first_name' => 'Bernadeth',          'middle_name' => 'T.',  'last_name' => 'Nacua',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 172, 'first_name' => 'Rodelia',            'middle_name' => 'T.',  'last_name' => 'Arancon',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 173, 'first_name' => 'Annabelle',          'middle_name' => 'T.',  'last_name' => 'Verula',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 174, 'first_name' => 'Jechris',            'middle_name' => 'O.',  'last_name' => 'Villanosa',          'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 175, 'first_name' => 'Julie',              'middle_name' => null,  'last_name' => 'Ebal',               'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 176, 'first_name' => 'Rebecca',            'middle_name' => 'A.',  'last_name' => 'Dilla',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 177, 'first_name' => 'John Fed',           'middle_name' => 'A.',  'last_name' => 'Cariaga',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 178, 'first_name' => 'Eastine',            'middle_name' => 'P.',  'last_name' => 'Taneo',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 179, 'first_name' => 'Kenneth Jay',        'middle_name' => 'Q.',  'last_name' => 'Abueva',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 180, 'first_name' => 'Kenneth',            'middle_name' => 'M.',  'last_name' => 'Kempis',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 181, 'first_name' => 'Dyan',               'middle_name' => 'D.',  'last_name' => 'Nacua',              'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 182, 'first_name' => 'Kelvin',             'middle_name' => 'T.',  'last_name' => 'Salvan',             'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 183, 'first_name' => 'Gracegift',          'middle_name' => 'E.',  'last_name' => 'Cabanas',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 184, 'first_name' => 'AILEL ROSE',         'middle_name' => 'S.',  'last_name' => 'ASEQUIA',            'created_at' => $now, 'updated_at' => $now],
            ['personnel_id' => 185, 'first_name' => 'Mmary Rod',          'middle_name' => 'C.',  'last_name' => 'Villastique',        'created_at' => $now, 'updated_at' => $now],
            // Added from latest SQL dump
            ['personnel_id' => 186, 'first_name' => 'Malyn',              'middle_name' => 'B.',  'last_name' => 'Lumacad',            'created_at' => $now, 'updated_at' => $now],
        ]);

        DB::statement('ALTER TABLE personnels AUTO_INCREMENT = 187;');
    }
}

// namespace Database\Seeders;

// use Illuminate\Database\Seeder;
// use Illuminate\Support\Facades\DB;

// class PersonnelSeeder extends Seeder
// {
//     public function run(): void
//     {
//         DB::statement('SET FOREIGN_KEY_CHECKS=0;');
//         DB::table('personnels')->truncate();
//         DB::statement('SET FOREIGN_KEY_CHECKS=1;');

//         $now = now();

//         DB::table('personnels')->insert([
//             ['personnel_id' => 1,   'first_name' => 'ATTY. JAYFRANCIS',   'middle_name' => 'D.',  'last_name' => 'BAGO',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 2,   'first_name' => 'Danilo',             'middle_name' => 'A.',  'last_name' => 'Paraguya',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 3,   'first_name' => 'Carla Niña',         'middle_name' => 'S.',  'last_name' => 'Salomon',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 4,   'first_name' => 'Elensita',           'middle_name' => 'V.',  'last_name' => 'Piit',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 5,   'first_name' => 'Karen',              'middle_name' => 'I.',  'last_name' => 'Barangot',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 6,   'first_name' => 'Noelene Joy',        'middle_name' => 'B.',  'last_name' => 'Jadumas',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 7,   'first_name' => 'Ray Amor',           'middle_name' => 'L.',  'last_name' => 'Arce',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 8,   'first_name' => 'Monico',             'middle_name' => 'B.',  'last_name' => 'Burgos',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 9,   'first_name' => 'Helen',              'middle_name' => 'A.',  'last_name' => 'Baquiro',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 10,  'first_name' => 'Aaron',              'middle_name' => 'M.',  'last_name' => 'Vacalares',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 11,  'first_name' => 'JOSEPH',             'middle_name' => 'A.',  'last_name' => 'ACTUB',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 12,  'first_name' => 'MAISIE',             'middle_name' => 'M.',  'last_name' => 'QUIDELLA',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 13,  'first_name' => 'Rezan',              'middle_name' => 'M.',  'last_name' => 'Cagatan',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 14,  'first_name' => 'Trishia Dominique',  'middle_name' => 'Z.',  'last_name' => 'Pitogo',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 15,  'first_name' => 'CHERRYL',            'middle_name' => 'G.',  'last_name' => 'MAGNETICO',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 16,  'first_name' => 'Gerald Kim',         'middle_name' => 'U.',  'last_name' => 'Garcia',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 17,  'first_name' => 'Rene',               'middle_name' => 'D.',  'last_name' => 'Magboo',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 18,  'first_name' => 'ENGR. ROMEL',        'middle_name' => 'C.',  'last_name' => 'LONOY REE',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 19,  'first_name' => 'Maebel Lou',         'middle_name' => 'A.',  'last_name' => 'Tedlos',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 20,  'first_name' => 'Daisy Mar',          'middle_name' => 'Q.',  'last_name' => 'Autida',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 21,  'first_name' => 'Efren',              'middle_name' => 'A.',  'last_name' => 'Daayata Jr.',        'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 22,  'first_name' => 'Edsil',              'middle_name' => 'V.',  'last_name' => 'Saarenas',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 23,  'first_name' => 'Leonardo',           'middle_name' => 'M.',  'last_name' => 'Cagalawan',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 24,  'first_name' => 'Dionisio',           'middle_name' => 'G.',  'last_name' => 'Montemayor III',     'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 25,  'first_name' => 'Odette',             'middle_name' => 'P.',  'last_name' => 'Galangke',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 26,  'first_name' => 'CANDIDO',            'middle_name' => 'M.',  'last_name' => 'DALIGDIG JR.',       'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 27,  'first_name' => 'DANILO',             'middle_name' => 'E.',  'last_name' => 'DAROY JR.',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 28,  'first_name' => 'Clessa Monique',     'middle_name' => 'O.',  'last_name' => 'Garces',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 29,  'first_name' => 'Rhally Mae',         'middle_name' => 'G.',  'last_name' => 'Piit',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 30,  'first_name' => 'Chizarina',          'middle_name' => 'M.',  'last_name' => 'Ortigoza',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 31,  'first_name' => 'Neal Oliver',        'middle_name' => 'H.',  'last_name' => 'Actub',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 32,  'first_name' => 'Eliezer',            'middle_name' => 'A.',  'last_name' => 'Vacalares Jr',       'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 33,  'first_name' => 'Hermito',            'middle_name' => 'B.',  'last_name' => 'Laid Jr.',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 34,  'first_name' => 'Palmero',            'middle_name' => 'F.',  'last_name' => 'Ebonia',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 35,  'first_name' => 'Ana Karla',          'middle_name' => 'L.',  'last_name' => 'Cabrera',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 36,  'first_name' => 'Nestor',             'middle_name' => 'M.',  'last_name' => 'Sapio III',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 37,  'first_name' => 'Jeric John',         'middle_name' => 'P.',  'last_name' => 'Cagalawan',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 38,  'first_name' => 'Jeffrey',            'middle_name' => 'P.',  'last_name' => 'Puasan',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 39,  'first_name' => 'JOMAR FRANCO',       'middle_name' => 'D.',  'last_name' => 'BAGO',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 40,  'first_name' => 'Rhodelyn Mae',       'middle_name' => 'B.',  'last_name' => 'Roa',                'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 41,  'first_name' => 'Lani',               'middle_name' => 'Y.',  'last_name' => 'Lagra',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 42,  'first_name' => 'Ariel',              'middle_name' => 'V.',  'last_name' => 'Nob',                'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 43,  'first_name' => 'Jeford',             'middle_name' => 'P.',  'last_name' => 'Pastrana',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 44,  'first_name' => 'xxxxxxxxxxx',        'middle_name' => 'S.',  'last_name' => 'xxxxxxxx',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 45,  'first_name' => 'Enrico',             'middle_name' => null,  'last_name' => 'Fornoles',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 46,  'first_name' => 'Arcelie',            'middle_name' => 'C.',  'last_name' => 'Yasay',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 47,  'first_name' => 'Greg Ulysses',       'middle_name' => 'T.',  'last_name' => 'Obsioma',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 48,  'first_name' => 'ENGR. ROLAND',       'middle_name' => 'B.',  'last_name' => 'CAINHOG',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 49,  'first_name' => 'Edgar',              'middle_name' => 'C.',  'last_name' => 'Cariliman',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 50,  'first_name' => 'GREG',               'middle_name' => 'M.',  'last_name' => 'RADAZA MBA',         'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 51,  'first_name' => 'Maria Fe',           'middle_name' => 'O.',  'last_name' => 'Tampus',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 52,  'first_name' => 'Ralph',              'middle_name' => null,  'last_name' => 'Basalo',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 53,  'first_name' => 'Armando',            'middle_name' => 'E.',  'last_name' => 'Yana',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 54,  'first_name' => 'HILAIRE MAY',        'middle_name' => 'F.',  'last_name' => 'BACULIO CPA',        'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 55,  'first_name' => 'Jonathan',           'middle_name' => 'L.',  'last_name' => 'Loreno',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 56,  'first_name' => 'Ma. Jessiel',        'middle_name' => 'L.',  'last_name' => 'Gutierrez',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 57,  'first_name' => 'Ruby',               'middle_name' => 'C.',  'last_name' => 'Mangubat',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 58,  'first_name' => 'Shaira Joyce',       'middle_name' => 'P.',  'last_name' => 'Edera',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 59,  'first_name' => 'Cecilia',            'middle_name' => 'A.',  'last_name' => 'Actub',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 60,  'first_name' => 'LALAINE',            'middle_name' => 'M.',  'last_name' => 'CARILIMAN',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 61,  'first_name' => 'Enn Meriell',        'middle_name' => 'L.',  'last_name' => 'Largo',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 62,  'first_name' => 'Ruel',               'middle_name' => 'Y.',  'last_name' => 'Gamolo',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 63,  'first_name' => 'Jean',               'middle_name' => 'L.',  'last_name' => 'Bacadon',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 64,  'first_name' => 'Daisy Mae',          'middle_name' => 'A.',  'last_name' => 'Abellanosa',         'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 65,  'first_name' => 'Cherrelyn',          'middle_name' => 'C.',  'last_name' => 'Aba',                'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 66,  'first_name' => 'Danilo',             'middle_name' => 'G.',  'last_name' => 'Yana Jr.',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 67,  'first_name' => 'Ed Paulo',           'middle_name' => 'N.',  'last_name' => 'Estrada',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 68,  'first_name' => 'Fe',                 'middle_name' => 'Y.',  'last_name' => 'Naalatan',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 69,  'first_name' => 'Niño Jose',          'middle_name' => 'B.',  'last_name' => 'Macasarte',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 70,  'first_name' => 'Adiodeta',           'middle_name' => 'B.',  'last_name' => 'Malaya',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 71,  'first_name' => 'Kim',                'middle_name' => 'S.',  'last_name' => 'Lazo',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 72,  'first_name' => 'EDGAR',              'middle_name' => 'C.',  'last_name' => 'OLACO REA REB',      'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 73,  'first_name' => 'Rosalie',            'middle_name' => 'E.',  'last_name' => 'Buna',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 74,  'first_name' => 'Nick',               'middle_name' => 'O.',  'last_name' => 'Illana',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 75,  'first_name' => 'Joel',               'middle_name' => 'A.',  'last_name' => 'Piit',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 76,  'first_name' => 'Mae Glaiza',         'middle_name' => 'T.',  'last_name' => 'Paclar',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 77,  'first_name' => 'Fatima Anne',        'middle_name' => 'S.',  'last_name' => 'Pagador',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 78,  'first_name' => 'Arnel',              'middle_name' => 'M.',  'last_name' => 'Apdohan',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 79,  'first_name' => 'Eva',                'middle_name' => 'R.',  'last_name' => 'Togonon',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 80,  'first_name' => 'Reno',               'middle_name' => 'D.',  'last_name' => 'German',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 81,  'first_name' => 'EMILY GRACE',        'middle_name' => 'G.',  'last_name' => 'BANAL',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 82,  'first_name' => 'Jovie',              'middle_name' => null,  'last_name' => 'Sabellina',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 83,  'first_name' => 'Glenn',              'middle_name' => 'D.',  'last_name' => 'Aracena',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 84,  'first_name' => 'Deanne Ritz',        'middle_name' => 'L.',  'last_name' => 'Carupo',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 85,  'first_name' => 'Mark Louise',        'middle_name' => 'L.',  'last_name' => 'Maleriado',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 86,  'first_name' => 'Leonila',            'middle_name' => 'B.',  'last_name' => 'Dablio',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 87,  'first_name' => 'Ma. Teresa',         'middle_name' => 'L.',  'last_name' => 'Padero',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 88,  'first_name' => 'Marivic',            'middle_name' => 'E.',  'last_name' => 'Añora',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 89,  'first_name' => 'Angelita',           'middle_name' => 'Y.',  'last_name' => 'Malinao',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 90,  'first_name' => 'Aira Coleen',        'middle_name' => null,  'last_name' => 'Muring',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 91,  'first_name' => 'Nadine',             'middle_name' => 'M.',  'last_name' => 'Ebarat',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 92,  'first_name' => 'Hannah',             'middle_name' => 'S.',  'last_name' => 'Licawat',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 93,  'first_name' => 'Janeth',             'middle_name' => 'R.',  'last_name' => 'Tan-gan',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 94,  'first_name' => 'Mae',                'middle_name' => 'M.',  'last_name' => 'Cervantes',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 95,  'first_name' => 'Hazel',              'middle_name' => 'T.',  'last_name' => 'Villiones',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 96,  'first_name' => 'Jennifer',           'middle_name' => null,  'last_name' => 'Fabricante',         'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 97,  'first_name' => 'Hazel',              'middle_name' => 'A.',  'last_name' => 'Bombeo',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 98,  'first_name' => 'Lanny',              'middle_name' => 'L.',  'last_name' => 'Realista',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 99,  'first_name' => 'Joy',                'middle_name' => 'S.',  'last_name' => 'Cosep',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 100, 'first_name' => 'Rejan Mae',          'middle_name' => 'R.',  'last_name' => 'Tan-gan',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 101, 'first_name' => 'Antonio',            'middle_name' => 'M.',  'last_name' => 'Abesamis',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 102, 'first_name' => 'Jomar',              'middle_name' => 'E.',  'last_name' => 'Madronal',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 103, 'first_name' => 'Micy',               'middle_name' => 'C.',  'last_name' => 'Yañez',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 104, 'first_name' => 'Rene',               'middle_name' => 'J.',  'last_name' => 'Barangot',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 105, 'first_name' => 'Aissa',              'middle_name' => 'R.',  'last_name' => 'Orog',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 106, 'first_name' => 'Glenda',             'middle_name' => 'D.',  'last_name' => 'Babatido',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 107, 'first_name' => 'MALYN',              'middle_name' => 'L.',  'last_name' => 'SARMIENTO RSW',      'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 108, 'first_name' => 'Liberty',            'middle_name' => 'L.',  'last_name' => 'Pabilona',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 109, 'first_name' => 'KATHLEEN MAE',       'middle_name' => 'L.',  'last_name' => 'ABORDO',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 110, 'first_name' => 'Marcia Erra',        'middle_name' => 'O.',  'last_name' => 'Balansag',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 111, 'first_name' => 'Dedith',             'middle_name' => 'G.',  'last_name' => 'Mabao',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 112, 'first_name' => 'Chyrel',             'middle_name' => 'B.',  'last_name' => 'Racines',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 113, 'first_name' => 'EDDIE',              'middle_name' => 'C.',  'last_name' => 'MAAPE JR.',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 114, 'first_name' => 'Mailyn',             'middle_name' => 'C.',  'last_name' => 'Quiblat',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 115, 'first_name' => 'John Paul Ceasar',   'middle_name' => 'L.',  'last_name' => 'Lacandula',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 116, 'first_name' => 'Calvin',             'middle_name' => 'A.',  'last_name' => 'Arevalo Jr.',        'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 117, 'first_name' => 'Kriza Gay',          'middle_name' => 'O.',  'last_name' => 'Obradas',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 118, 'first_name' => 'Benjamin',           'middle_name' => 'D.',  'last_name' => 'Macadenden III',     'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 119, 'first_name' => 'Bimbo',              'middle_name' => 'C.',  'last_name' => 'Legaspi',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 120, 'first_name' => 'Vincent Jay',        'middle_name' => null,  'last_name' => 'Enriquez',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 121, 'first_name' => 'Cindy',              'middle_name' => 'M.',  'last_name' => 'Quimanhan',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 122, 'first_name' => 'Julito',             'middle_name' => 'M.',  'last_name' => 'Quiblat',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 123, 'first_name' => 'ENGR. LILIBETH',     'middle_name' => 'S.',  'last_name' => 'UY',                 'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 124, 'first_name' => 'Patrick',            'middle_name' => 'D.',  'last_name' => 'Opeña',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 125, 'first_name' => 'Jefrey',             'middle_name' => 'V.',  'last_name' => 'Pakino',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 126, 'first_name' => 'Charlie',            'middle_name' => 'Q.',  'last_name' => 'Igloria Jr.',        'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 127, 'first_name' => 'Edsyll',             'middle_name' => 'M.',  'last_name' => 'Esmeralda',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 128, 'first_name' => 'Bryle',              'middle_name' => 'C.',  'last_name' => 'Opena',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 129, 'first_name' => 'Michael',            'middle_name' => 'C.',  'last_name' => 'Doydora',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 130, 'first_name' => 'Bernie',             'middle_name' => 'C.',  'last_name' => 'Vacalares',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 131, 'first_name' => 'Bernard',            'middle_name' => 'L.',  'last_name' => 'Paclar',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 132, 'first_name' => 'Apollo',             'middle_name' => 'E.',  'last_name' => 'Madelo',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 133, 'first_name' => 'Florence Sheila',    'middle_name' => 'M.',  'last_name' => 'Jacalan',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 134, 'first_name' => 'Melbin',             'middle_name' => 'B.',  'last_name' => 'Bulaso',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 135, 'first_name' => 'Edgar',              'middle_name' => 'D.',  'last_name' => 'Rago',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 136, 'first_name' => 'Gonzalo',            'middle_name' => 'A.',  'last_name' => 'Anteporta',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 137, 'first_name' => 'Vifred',             'middle_name' => 'C.',  'last_name' => 'Cagalawan',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 138, 'first_name' => 'Rey',                'middle_name' => 'L.',  'last_name' => 'Baculio',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 139, 'first_name' => 'Edsel',              'middle_name' => 'S.',  'last_name' => 'Igloria',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 140, 'first_name' => 'Ceasar',             'middle_name' => 'G.',  'last_name' => 'Lacandula',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 141, 'first_name' => 'Michael',            'middle_name' => 'E.',  'last_name' => 'Escaba',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 142, 'first_name' => 'Kenneth John',       'middle_name' => 'L.',  'last_name' => 'Padero',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 143, 'first_name' => 'Alfred',             'middle_name' => 'C.',  'last_name' => 'Galdo',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 144, 'first_name' => 'ENGR. JESON',        'middle_name' => 'G.',  'last_name' => 'JACALAN',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 145, 'first_name' => 'Lester',             'middle_name' => 'L.',  'last_name' => 'Boter',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 146, 'first_name' => 'ENGR. RANDOLPH',     'middle_name' => 'Q.',  'last_name' => 'HALLASGO',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 147, 'first_name' => 'Loelle Joseph',      'middle_name' => 'D.',  'last_name' => 'Pacana',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 148, 'first_name' => 'Elbert',             'middle_name' => 'A.',  'last_name' => 'Yasay',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 149, 'first_name' => 'Daisy',              'middle_name' => 'B.',  'last_name' => 'Almazan',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 150, 'first_name' => 'Ulysses Sosa',       'middle_name' => null,  'last_name' => 'Palomares',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 151, 'first_name' => 'DR. JANESSA',        'middle_name' => 'P.',  'last_name' => 'BEARNEZA',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 152, 'first_name' => 'ARIEL BRIAN',        'middle_name' => 'Y.',  'last_name' => 'ORTIGOZA',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 153, 'first_name' => 'Jailyne Jane',       'middle_name' => 'G.',  'last_name' => 'Cartagena',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 154, 'first_name' => 'ETHEL RAE',          'middle_name' => 'C.',  'last_name' => 'REYES',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 155, 'first_name' => 'Shirley',            'middle_name' => 'C.',  'last_name' => 'Centillas',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 156, 'first_name' => 'James Bryan',        'middle_name' => 'Q.',  'last_name' => 'Dunque',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 157, 'first_name' => 'Jonathan',           'middle_name' => 'I.',  'last_name' => 'Dablio',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 158, 'first_name' => 'Melchora',           'middle_name' => 'G.',  'last_name' => 'Hanoyan',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 159, 'first_name' => 'Oliver',             'middle_name' => null,  'last_name' => 'Baculina',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 160, 'first_name' => 'RINA',               'middle_name' => 'A.',  'last_name' => 'CALIZA',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 161, 'first_name' => 'Daniel',             'middle_name' => 'O.',  'last_name' => 'Mag-away',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 162, 'first_name' => 'Rex Ali',            'middle_name' => 'G.',  'last_name' => 'Janubas',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 163, 'first_name' => 'Joefel',             'middle_name' => 'P.',  'last_name' => 'Lagutin',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 164, 'first_name' => 'RYAN',               'middle_name' => 'Y.',  'last_name' => 'DALAGUIADO',         'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 165, 'first_name' => 'Dolorita',           'middle_name' => 'N.',  'last_name' => 'Arao',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 166, 'first_name' => 'Alma',               'middle_name' => 'T.',  'last_name' => 'Gurrea',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 167, 'first_name' => 'Ron Jake',           'middle_name' => 'I.',  'last_name' => 'Romero',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 168, 'first_name' => 'DR. NIELSON',        'middle_name' => 'D.',  'last_name' => 'BATION',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 169, 'first_name' => 'Sophomore',          'middle_name' => 'T.',  'last_name' => 'Vacalares',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 170, 'first_name' => 'Ruben',              'middle_name' => 'B.',  'last_name' => 'Madriaga',           'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 171, 'first_name' => 'Bernadeth',          'middle_name' => 'T.',  'last_name' => 'Nacua',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 172, 'first_name' => 'Rodelia',            'middle_name' => 'T.',  'last_name' => 'Arancon',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 173, 'first_name' => 'Annabelle',          'middle_name' => 'T.',  'last_name' => 'Verula',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 174, 'first_name' => 'Jechris',            'middle_name' => 'O.',  'last_name' => 'Villanosa',          'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 175, 'first_name' => 'Julie',              'middle_name' => null,  'last_name' => 'Ebal',               'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 176, 'first_name' => 'Rebecca',            'middle_name' => 'A.',  'last_name' => 'Dilla',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 177, 'first_name' => 'John Fed',           'middle_name' => 'A.',  'last_name' => 'Cariaga',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 178, 'first_name' => 'Eastine',            'middle_name' => 'P.',  'last_name' => 'Taneo',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 179, 'first_name' => 'Kenneth Jay',        'middle_name' => 'Q.',  'last_name' => 'Abueva',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 180, 'first_name' => 'Kenneth',            'middle_name' => 'M.',  'last_name' => 'Kempis',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 181, 'first_name' => 'Dyan',               'middle_name' => 'D.',  'last_name' => 'Nacua',              'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 182, 'first_name' => 'Kelvin',             'middle_name' => 'T.',  'last_name' => 'Salvan',             'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 183, 'first_name' => 'Gracegift',          'middle_name' => 'E.',  'last_name' => 'Cabanas',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 184, 'first_name' => 'AILEL ROSE',         'middle_name' => 'S.',  'last_name' => 'ASEQUIA',            'created_at' => $now, 'updated_at' => $now],
//             ['personnel_id' => 185, 'first_name' => 'Mmary Rod',          'middle_name' => 'C.',  'last_name' => 'Villastique',        'created_at' => $now, 'updated_at' => $now],
//         ]);

//         // Reset auto-increment
//         DB::statement('ALTER TABLE personnels AUTO_INCREMENT = 186;');
//     }
// }