<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantillaAssignmentSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('plantilla_assignments')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = now();

        $records = [
            ['assignment_id' => 1,   'plantilla_position_id' => 1,   'personnel_id' => 1,   'assignment_date' => '2022-07-01'],
            ['assignment_id' => 2,   'plantilla_position_id' => 2,   'personnel_id' => 2,   'assignment_date' => '2021-09-01'],
            ['assignment_id' => 3,   'plantilla_position_id' => 3,   'personnel_id' => 3,   'assignment_date' => '2021-12-01'],
            ['assignment_id' => 4,   'plantilla_position_id' => 4,   'personnel_id' => 179, 'assignment_date' => '2025-09-01'],
            ['assignment_id' => 5,   'plantilla_position_id' => 5,   'personnel_id' => 5,   'assignment_date' => '2010-03-05'],
            ['assignment_id' => 6,   'plantilla_position_id' => 6,   'personnel_id' => 4,   'assignment_date' => '2006-10-04'],
            ['assignment_id' => 7,   'plantilla_position_id' => 7,   'personnel_id' => 7,   'assignment_date' => '2021-01-04'],
            ['assignment_id' => 8,   'plantilla_position_id' => 8,   'personnel_id' => 8,   'assignment_date' => '2023-09-01'],
            ['assignment_id' => 9,   'plantilla_position_id' => 9,   'personnel_id' => 9,   'assignment_date' => '2021-01-04'],
            ['assignment_id' => 10,  'plantilla_position_id' => 10,  'personnel_id' => 10,  'assignment_date' => '2020-01-02'],
            ['assignment_id' => 11,  'plantilla_position_id' => 11,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 12,  'plantilla_position_id' => 12,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 13,  'plantilla_position_id' => 13,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 14,  'plantilla_position_id' => 14,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 15,  'plantilla_position_id' => 15,  'personnel_id' => 178, 'assignment_date' => '2025-09-01'],
            ['assignment_id' => 16,  'plantilla_position_id' => 16,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 17,  'plantilla_position_id' => 17,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 18,  'plantilla_position_id' => 18,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 19,  'plantilla_position_id' => 19,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 20,  'plantilla_position_id' => 20,  'personnel_id' => 6,   'assignment_date' => '2021-01-04'],
            ['assignment_id' => 21,  'plantilla_position_id' => 110, 'personnel_id' => 50,  'assignment_date' => '2018-06-01'],
            ['assignment_id' => 22,  'plantilla_position_id' => 114, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 23,  'plantilla_position_id' => 111, 'personnel_id' => 51,  'assignment_date' => '2021-01-04'],
            ['assignment_id' => 24,  'plantilla_position_id' => 115, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 25,  'plantilla_position_id' => 112, 'personnel_id' => 52,  'assignment_date' => '2022-02-02'],
            ['assignment_id' => 26,  'plantilla_position_id' => 113, 'personnel_id' => 53,  'assignment_date' => '2020-07-01'],
            ['assignment_id' => 27,  'plantilla_position_id' => 21,  'personnel_id' => 180, 'assignment_date' => '2022-07-04'],
            ['assignment_id' => 28,  'plantilla_position_id' => 22,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 29,  'plantilla_position_id' => 23,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 30,  'plantilla_position_id' => 24,  'personnel_id' => 181, 'assignment_date' => '2026-01-05'],
            ['assignment_id' => 31,  'plantilla_position_id' => 25,  'personnel_id' => 182, 'assignment_date' => '2026-03-23'],
            ['assignment_id' => 32,  'plantilla_position_id' => 63,  'personnel_id' => 27,  'assignment_date' => '2022-07-01'],
            ['assignment_id' => 33,  'plantilla_position_id' => 64,  'personnel_id' => 28,  'assignment_date' => '2025-07-01'],
            ['assignment_id' => 34,  'plantilla_position_id' => 65,  'personnel_id' => 35,  'assignment_date' => '2025-07-01'],
            ['assignment_id' => 35,  'plantilla_position_id' => 66,  'personnel_id' => 32,  'assignment_date' => '2022-07-01'],
            ['assignment_id' => 36,  'plantilla_position_id' => 67,  'personnel_id' => 33,  'assignment_date' => '2025-07-01'],
            ['assignment_id' => 37,  'plantilla_position_id' => 68,  'personnel_id' => 30,  'assignment_date' => '2010-07-10'],
            ['assignment_id' => 38,  'plantilla_position_id' => 69,  'personnel_id' => 31,  'assignment_date' => '2025-07-01'],
            ['assignment_id' => 39,  'plantilla_position_id' => 70,  'personnel_id' => 34,  'assignment_date' => '2022-07-01'],
            ['assignment_id' => 40,  'plantilla_position_id' => 71,  'personnel_id' => 29,  'assignment_date' => '2022-07-01'],
            ['assignment_id' => 41,  'plantilla_position_id' => 72,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 42,  'plantilla_position_id' => 73,  'personnel_id' => 37,  'assignment_date' => '2023-12-04'],
            ['assignment_id' => 43,  'plantilla_position_id' => 74,  'personnel_id' => 38,  'assignment_date' => '2022-09-01'],
            ['assignment_id' => 44,  'plantilla_position_id' => 30,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 45,  'plantilla_position_id' => 26,  'personnel_id' => 11,  'assignment_date' => '2025-02-03'],
            ['assignment_id' => 46,  'plantilla_position_id' => 27,  'personnel_id' => 12,  'assignment_date' => '2016-10-20'],
            ['assignment_id' => 47,  'plantilla_position_id' => 31,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 48,  'plantilla_position_id' => 32,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 49,  'plantilla_position_id' => 28,  'personnel_id' => 14,  'assignment_date' => '2021-08-16'],
            ['assignment_id' => 50,  'plantilla_position_id' => 29,  'personnel_id' => 13,  'assignment_date' => '2020-07-01'],
            ['assignment_id' => 51,  'plantilla_position_id' => 33,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 52,  'plantilla_position_id' => 34,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 53,  'plantilla_position_id' => 35,  'personnel_id' => 15,  'assignment_date' => '2024-10-01'],
            ['assignment_id' => 54,  'plantilla_position_id' => 38,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 55,  'plantilla_position_id' => 36,  'personnel_id' => 16,  'assignment_date' => '2022-03-01'],
            ['assignment_id' => 56,  'plantilla_position_id' => 37,  'personnel_id' => 17,  'assignment_date' => '2022-03-01'],
            ['assignment_id' => 57,  'plantilla_position_id' => 39,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 58,  'plantilla_position_id' => 75,  'personnel_id' => 39,  'assignment_date' => '2022-09-01'],
            ['assignment_id' => 59,  'plantilla_position_id' => 80,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 60,  'plantilla_position_id' => 76,  'personnel_id' => 40,  'assignment_date' => '2024-03-01'],
            ['assignment_id' => 61,  'plantilla_position_id' => 81,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 62,  'plantilla_position_id' => 82,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 63,  'plantilla_position_id' => 77,  'personnel_id' => 41,  'assignment_date' => '2021-12-01'],
            ['assignment_id' => 64,  'plantilla_position_id' => 83,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 65,  'plantilla_position_id' => 78,  'personnel_id' => 42,  'assignment_date' => '2021-12-01'],
            ['assignment_id' => 66,  'plantilla_position_id' => 84,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 67,  'plantilla_position_id' => 79,  'personnel_id' => 43,  'assignment_date' => '2016-01-25'],
            ['assignment_id' => 68,  'plantilla_position_id' => 85,  'personnel_id' => 183, 'assignment_date' => '2021-12-01'],
            ['assignment_id' => 69,  'plantilla_position_id' => 86,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 70,  'plantilla_position_id' => 87,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 71,  'plantilla_position_id' => 88,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 72,  'plantilla_position_id' => 89,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 73,  'plantilla_position_id' => 59,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 74,  'plantilla_position_id' => 58,  'personnel_id' => 25,  'assignment_date' => '2021-09-01'],
            ['assignment_id' => 75,  'plantilla_position_id' => 61,  'personnel_id' => 26,  'assignment_date' => '2022-02-16'],
            ['assignment_id' => 76,  'plantilla_position_id' => 60,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 77,  'plantilla_position_id' => 62,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 78,  'plantilla_position_id' => 256, 'personnel_id' => 151, 'assignment_date' => '2024-10-01'],
            ['assignment_id' => 79,  'plantilla_position_id' => 90,  'personnel_id' => 184, 'assignment_date' => '2019-01-03'],
            ['assignment_id' => 80,  'plantilla_position_id' => 94,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 81,  'plantilla_position_id' => 95,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 82,  'plantilla_position_id' => 96,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 83,  'plantilla_position_id' => 91,  'personnel_id' => 45,  'assignment_date' => '2020-02-03'],
            ['assignment_id' => 84,  'plantilla_position_id' => 97,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 85,  'plantilla_position_id' => 98,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 86,  'plantilla_position_id' => 99,  'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 87,  'plantilla_position_id' => 100, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 88,  'plantilla_position_id' => 101, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 89,  'plantilla_position_id' => 102, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 90,  'plantilla_position_id' => 92,  'personnel_id' => 46,  'assignment_date' => '2008-02-11'],
            ['assignment_id' => 91,  'plantilla_position_id' => 93,  'personnel_id' => 47,  'assignment_date' => '2024-02-02'],
            ['assignment_id' => 92,  'plantilla_position_id' => 103, 'personnel_id' => 48,  'assignment_date' => '2021-04-05'],
            ['assignment_id' => 93,  'plantilla_position_id' => 105, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 94,  'plantilla_position_id' => 106, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 95,  'plantilla_position_id' => 107, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 96,  'plantilla_position_id' => 108, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 97,  'plantilla_position_id' => 109, 'personnel_id' => 185, 'assignment_date' => '2025-09-01'],
            ['assignment_id' => 98,  'plantilla_position_id' => 104, 'personnel_id' => 49,  'assignment_date' => '2009-11-23'],
            ['assignment_id' => 99,  'plantilla_position_id' => 116, 'personnel_id' => 54,  'assignment_date' => '2018-08-01'],
            ['assignment_id' => 100, 'plantilla_position_id' => 117, 'personnel_id' => 55,  'assignment_date' => '2019-01-03'],
            ['assignment_id' => 101, 'plantilla_position_id' => 118, 'personnel_id' => 56,  'assignment_date' => '2019-07-16'],
            ['assignment_id' => 102, 'plantilla_position_id' => 119, 'personnel_id' => 57,  'assignment_date' => '2023-08-01'],
            ['assignment_id' => 103, 'plantilla_position_id' => 120, 'personnel_id' => 58,  'assignment_date' => '2024-10-01'],
            ['assignment_id' => 104, 'plantilla_position_id' => 121, 'personnel_id' => 59,  'assignment_date' => '2014-03-07'],
            ['assignment_id' => 105, 'plantilla_position_id' => 122, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 106, 'plantilla_position_id' => 123, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 107, 'plantilla_position_id' => 124, 'personnel_id' => 60,  'assignment_date' => '2011-11-14'],
            ['assignment_id' => 108, 'plantilla_position_id' => 125, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 109, 'plantilla_position_id' => 126, 'personnel_id' => 62,  'assignment_date' => '2018-06-01'],
            ['assignment_id' => 110, 'plantilla_position_id' => 127, 'personnel_id' => 63,  'assignment_date' => '2018-06-01'],
            ['assignment_id' => 111, 'plantilla_position_id' => 128, 'personnel_id' => 64,  'assignment_date' => '2019-12-02'],
            ['assignment_id' => 112, 'plantilla_position_id' => 129, 'personnel_id' => 65,  'assignment_date' => '2023-01-09'],
            ['assignment_id' => 113, 'plantilla_position_id' => 136, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 114, 'plantilla_position_id' => 130, 'personnel_id' => 66,  'assignment_date' => '2021-07-01'],
            ['assignment_id' => 115, 'plantilla_position_id' => 131, 'personnel_id' => 67,  'assignment_date' => '2020-08-03'],
            ['assignment_id' => 116, 'plantilla_position_id' => 132, 'personnel_id' => 68,  'assignment_date' => '2011-07-11'],
            ['assignment_id' => 117, 'plantilla_position_id' => 133, 'personnel_id' => 69,  'assignment_date' => '2019-11-04'],
            ['assignment_id' => 118, 'plantilla_position_id' => 137, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 119, 'plantilla_position_id' => 138, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 120, 'plantilla_position_id' => 139, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 121, 'plantilla_position_id' => 140, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 122, 'plantilla_position_id' => 134, 'personnel_id' => 70,  'assignment_date' => '2022-03-01'],
            ['assignment_id' => 123, 'plantilla_position_id' => 135, 'personnel_id' => 71,  'assignment_date' => '2010-02-15'],
            ['assignment_id' => 124, 'plantilla_position_id' => 141, 'personnel_id' => 72,  'assignment_date' => '2012-08-06'],
            ['assignment_id' => 125, 'plantilla_position_id' => 150, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 126, 'plantilla_position_id' => 149, 'personnel_id' => 80,  'assignment_date' => '2025-01-02'],
            ['assignment_id' => 127, 'plantilla_position_id' => 151, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 128, 'plantilla_position_id' => 152, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 129, 'plantilla_position_id' => 148, 'personnel_id' => 79,  'assignment_date' => '2020-07-01'],
            ['assignment_id' => 130, 'plantilla_position_id' => 293, 'personnel_id' => 73,  'assignment_date' => '2020-07-01'],
            ['assignment_id' => 131, 'plantilla_position_id' => 294, 'personnel_id' => 75,  'assignment_date' => '2021-02-01'],
            ['assignment_id' => 132, 'plantilla_position_id' => 295, 'personnel_id' => 76,  'assignment_date' => '2021-01-04'],
            ['assignment_id' => 133, 'plantilla_position_id' => 296, 'personnel_id' => 77,  'assignment_date' => '2021-01-04'],
            ['assignment_id' => 134, 'plantilla_position_id' => 297, 'personnel_id' => 78,  'assignment_date' => '2019-10-16'],
            ['assignment_id' => 135, 'plantilla_position_id' => 153, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 136, 'plantilla_position_id' => 179, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 137, 'plantilla_position_id' => 180, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 138, 'plantilla_position_id' => 181, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 139, 'plantilla_position_id' => 154, 'personnel_id' => 82,  'assignment_date' => '2023-06-01'],
            ['assignment_id' => 140, 'plantilla_position_id' => 155, 'personnel_id' => 83,  'assignment_date' => '2019-10-16'],
            ['assignment_id' => 141, 'plantilla_position_id' => 156, 'personnel_id' => 84,  'assignment_date' => '2024-08-01'],
            ['assignment_id' => 142, 'plantilla_position_id' => 157, 'personnel_id' => 85,  'assignment_date' => '2024-08-16'],
            ['assignment_id' => 143, 'plantilla_position_id' => 182, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 144, 'plantilla_position_id' => 183, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 145, 'plantilla_position_id' => 158, 'personnel_id' => 86,  'assignment_date' => '2026-09-16'],
            ['assignment_id' => 146, 'plantilla_position_id' => 159, 'personnel_id' => 87,  'assignment_date' => '2021-12-01'],
            ['assignment_id' => 147, 'plantilla_position_id' => 160, 'personnel_id' => 88,  'assignment_date' => '2016-03-11'],
            ['assignment_id' => 148, 'plantilla_position_id' => 161, 'personnel_id' => 89,  'assignment_date' => '2018-11-05'],
            ['assignment_id' => 149, 'plantilla_position_id' => 162, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 150, 'plantilla_position_id' => 163, 'personnel_id' => 91,  'assignment_date' => '2023-06-01'],
            ['assignment_id' => 151, 'plantilla_position_id' => 164, 'personnel_id' => 92,  'assignment_date' => '2024-08-01'],
            ['assignment_id' => 152, 'plantilla_position_id' => 184, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 153, 'plantilla_position_id' => 185, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 154, 'plantilla_position_id' => 165, 'personnel_id' => 100, 'assignment_date' => '2021-10-01'],
            ['assignment_id' => 155, 'plantilla_position_id' => 166, 'personnel_id' => 97,  'assignment_date' => '2024-10-01'],
            ['assignment_id' => 156, 'plantilla_position_id' => 167, 'personnel_id' => 94,  'assignment_date' => '2018-06-01'],
            ['assignment_id' => 157, 'plantilla_position_id' => 168, 'personnel_id' => 95,  'assignment_date' => '2018-07-16'],
            ['assignment_id' => 158, 'plantilla_position_id' => 169, 'personnel_id' => 96,  'assignment_date' => '2023-01-03'],
            ['assignment_id' => 159, 'plantilla_position_id' => 170, 'personnel_id' => 98,  'assignment_date' => '2024-08-16'],
            ['assignment_id' => 160, 'plantilla_position_id' => 171, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 161, 'plantilla_position_id' => 172, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 162, 'plantilla_position_id' => 186, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 163, 'plantilla_position_id' => 187, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 164, 'plantilla_position_id' => 188, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 165, 'plantilla_position_id' => 189, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 166, 'plantilla_position_id' => 190, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 167, 'plantilla_position_id' => 191, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 168, 'plantilla_position_id' => 173, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 169, 'plantilla_position_id' => 174, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 170, 'plantilla_position_id' => 175, 'personnel_id' => 103, 'assignment_date' => '2018-01-31'],
            ['assignment_id' => 171, 'plantilla_position_id' => 192, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 172, 'plantilla_position_id' => 176, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 173, 'plantilla_position_id' => 177, 'personnel_id' => 105, 'assignment_date' => '2021-07-01'],
            ['assignment_id' => 174, 'plantilla_position_id' => 178, 'personnel_id' => 106, 'assignment_date' => '2019-10-16'],
            ['assignment_id' => 175, 'plantilla_position_id' => 193, 'personnel_id' => 186, 'assignment_date' => '2023-08-18'],
            ['assignment_id' => 176, 'plantilla_position_id' => 194, 'personnel_id' => 108, 'assignment_date' => '2017-06-01'],
            ['assignment_id' => 177, 'plantilla_position_id' => 195, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 178, 'plantilla_position_id' => 199, 'personnel_id' => 109, 'assignment_date' => '2023-01-09'],
            ['assignment_id' => 179, 'plantilla_position_id' => 196, 'personnel_id' => 110, 'assignment_date' => '2017-10-06'],
            ['assignment_id' => 180, 'plantilla_position_id' => 197, 'personnel_id' => 111, 'assignment_date' => '2019-10-16'],
            ['assignment_id' => 181, 'plantilla_position_id' => 200, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 182, 'plantilla_position_id' => 201, 'personnel_id' => null, 'assignment_date' => null],
            ['assignment_id' => 183, 'plantilla_position_id' => 198, 'personnel_id' => 112, 'assignment_date' => '2009-06-01'],
        ];

        foreach (array_chunk($records, 50) as $chunk) {
            $rows = array_map(fn($r) => array_merge($r, ['created_at' => $now, 'updated_at' => $now]), $chunk);
            DB::table('plantilla_assignments')->insert($rows);
        }

        DB::statement('ALTER TABLE plantilla_assignments AUTO_INCREMENT = 184;');
    }
}

// namespace Database\Seeders;

// use Illuminate\Database\Seeder;
// use Illuminate\Support\Facades\DB;

// class PlantillaAssignmentSeeder extends Seeder
// {
//     public function run(): void
//     {
//         DB::statement('SET FOREIGN_KEY_CHECKS=0;');
//         DB::table('plantilla_assignments')->truncate();
//         DB::statement('SET FOREIGN_KEY_CHECKS=1;');

//         $now = now();

//         DB::table('plantilla_assignments')->insert([
//             ['assignment_id' => 1,   'plantilla_position_id' => 1,   'personnel_id' => 1,   'assignment_date' => '2022-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 2,   'plantilla_position_id' => 2,   'personnel_id' => 2,   'assignment_date' => '2021-09-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 3,   'plantilla_position_id' => 3,   'personnel_id' => 3,   'assignment_date' => '2021-12-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 4,   'plantilla_position_id' => 4,   'personnel_id' => 179, 'assignment_date' => '2025-09-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 5,   'plantilla_position_id' => 5,   'personnel_id' => 5,   'assignment_date' => '2010-03-05', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 6,   'plantilla_position_id' => 6,   'personnel_id' => 4,   'assignment_date' => '2006-10-04', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 7,   'plantilla_position_id' => 7,   'personnel_id' => 7,   'assignment_date' => '2021-01-04', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 8,   'plantilla_position_id' => 8,   'personnel_id' => 8,   'assignment_date' => '2023-09-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 9,   'plantilla_position_id' => 9,   'personnel_id' => 9,   'assignment_date' => '2021-01-04', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 10,  'plantilla_position_id' => 10,  'personnel_id' => 10,  'assignment_date' => '2020-01-02', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 11,  'plantilla_position_id' => 11,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 12,  'plantilla_position_id' => 12,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 13,  'plantilla_position_id' => 13,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 14,  'plantilla_position_id' => 14,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 15,  'plantilla_position_id' => 15,  'personnel_id' => 178, 'assignment_date' => '2025-09-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 16,  'plantilla_position_id' => 16,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 17,  'plantilla_position_id' => 17,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 18,  'plantilla_position_id' => 18,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 19,  'plantilla_position_id' => 19,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 20,  'plantilla_position_id' => 20,  'personnel_id' => 6,   'assignment_date' => '2021-01-04', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 21,  'plantilla_position_id' => 110, 'personnel_id' => 50,  'assignment_date' => '2018-06-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 22,  'plantilla_position_id' => 114, 'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 23,  'plantilla_position_id' => 111, 'personnel_id' => 51,  'assignment_date' => '2021-01-04', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 24,  'plantilla_position_id' => 115, 'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 25,  'plantilla_position_id' => 112, 'personnel_id' => 52,  'assignment_date' => '2022-02-02', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 26,  'plantilla_position_id' => 113, 'personnel_id' => 53,  'assignment_date' => '2020-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 27,  'plantilla_position_id' => 21,  'personnel_id' => 180, 'assignment_date' => '2022-07-04', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 28,  'plantilla_position_id' => 22,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 29,  'plantilla_position_id' => 23,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 30,  'plantilla_position_id' => 24,  'personnel_id' => 181, 'assignment_date' => '2026-01-05', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 31,  'plantilla_position_id' => 25,  'personnel_id' => 182, 'assignment_date' => '2026-03-23', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 32,  'plantilla_position_id' => 63,  'personnel_id' => 27,  'assignment_date' => '2022-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 33,  'plantilla_position_id' => 64,  'personnel_id' => 28,  'assignment_date' => '2025-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 34,  'plantilla_position_id' => 65,  'personnel_id' => 35,  'assignment_date' => '2025-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 35,  'plantilla_position_id' => 66,  'personnel_id' => 32,  'assignment_date' => '2022-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 36,  'plantilla_position_id' => 67,  'personnel_id' => 33,  'assignment_date' => '2025-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 37,  'plantilla_position_id' => 68,  'personnel_id' => 30,  'assignment_date' => '2010-07-10', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 38,  'plantilla_position_id' => 69,  'personnel_id' => 31,  'assignment_date' => '2025-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 39,  'plantilla_position_id' => 70,  'personnel_id' => 34,  'assignment_date' => '2022-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 40,  'plantilla_position_id' => 71,  'personnel_id' => 29,  'assignment_date' => '2022-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 41,  'plantilla_position_id' => 72,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 42,  'plantilla_position_id' => 73,  'personnel_id' => 37,  'assignment_date' => '2023-12-04', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 43,  'plantilla_position_id' => 74,  'personnel_id' => 38,  'assignment_date' => '2022-09-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 44,  'plantilla_position_id' => 30,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 45,  'plantilla_position_id' => 26,  'personnel_id' => 11,  'assignment_date' => '2025-02-03', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 46,  'plantilla_position_id' => 27,  'personnel_id' => 12,  'assignment_date' => '2016-10-20', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 47,  'plantilla_position_id' => 31,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 48,  'plantilla_position_id' => 32,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 49,  'plantilla_position_id' => 28,  'personnel_id' => 14,  'assignment_date' => '2021-08-16', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 50,  'plantilla_position_id' => 29,  'personnel_id' => 13,  'assignment_date' => '2020-07-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 51,  'plantilla_position_id' => 33,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 52,  'plantilla_position_id' => 34,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 53,  'plantilla_position_id' => 35,  'personnel_id' => 15,  'assignment_date' => '2024-10-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 54,  'plantilla_position_id' => 38,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 55,  'plantilla_position_id' => 36,  'personnel_id' => 16,  'assignment_date' => '2022-03-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 56,  'plantilla_position_id' => 37,  'personnel_id' => 17,  'assignment_date' => '2022-03-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 57,  'plantilla_position_id' => 39,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 58,  'plantilla_position_id' => 75,  'personnel_id' => 39,  'assignment_date' => '2022-09-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 59,  'plantilla_position_id' => 80,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 60,  'plantilla_position_id' => 76,  'personnel_id' => 40,  'assignment_date' => '2024-03-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 61,  'plantilla_position_id' => 81,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 62,  'plantilla_position_id' => 82,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 63,  'plantilla_position_id' => 77,  'personnel_id' => 41,  'assignment_date' => '2021-12-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 64,  'plantilla_position_id' => 83,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 65,  'plantilla_position_id' => 78,  'personnel_id' => 42,  'assignment_date' => '2021-12-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 66,  'plantilla_position_id' => 84,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 67,  'plantilla_position_id' => 79,  'personnel_id' => 43,  'assignment_date' => '2016-01-25', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 68,  'plantilla_position_id' => 85,  'personnel_id' => 183, 'assignment_date' => '2021-12-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 69,  'plantilla_position_id' => 86,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 70,  'plantilla_position_id' => 87,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 71,  'plantilla_position_id' => 88,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 72,  'plantilla_position_id' => 89,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 73,  'plantilla_position_id' => 59,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 74,  'plantilla_position_id' => 58,  'personnel_id' => 25,  'assignment_date' => '2021-09-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 75,  'plantilla_position_id' => 61,  'personnel_id' => 26,  'assignment_date' => '2022-02-16', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 76,  'plantilla_position_id' => 60,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 77,  'plantilla_position_id' => 62,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 78,  'plantilla_position_id' => 256, 'personnel_id' => 151, 'assignment_date' => '2024-10-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 79,  'plantilla_position_id' => 90,  'personnel_id' => 44,  'assignment_date' => '2019-01-03', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 80,  'plantilla_position_id' => 94,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 81,  'plantilla_position_id' => 95,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 82,  'plantilla_position_id' => 96,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 83,  'plantilla_position_id' => 91,  'personnel_id' => 45,  'assignment_date' => '2020-02-03', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 84,  'plantilla_position_id' => 97,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 85,  'plantilla_position_id' => 98,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 86,  'plantilla_position_id' => 99,  'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 87,  'plantilla_position_id' => 100, 'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 88,  'plantilla_position_id' => 101, 'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 89,  'plantilla_position_id' => 102, 'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 90,  'plantilla_position_id' => 92,  'personnel_id' => 46,  'assignment_date' => '2008-02-11', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 91,  'plantilla_position_id' => 93,  'personnel_id' => 47,  'assignment_date' => '2024-02-02', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 92,  'plantilla_position_id' => 103, 'personnel_id' => 48,  'assignment_date' => '2021-04-05', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 93,  'plantilla_position_id' => 105, 'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 94,  'plantilla_position_id' => 106, 'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 95,  'plantilla_position_id' => 107, 'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 96,  'plantilla_position_id' => 108, 'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 97,  'plantilla_position_id' => 109, 'personnel_id' => 185, 'assignment_date' => '2025-09-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 98,  'plantilla_position_id' => 104, 'personnel_id' => 49,  'assignment_date' => '2009-11-23', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 99,  'plantilla_position_id' => 116, 'personnel_id' => 54,  'assignment_date' => '2018-08-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 100, 'plantilla_position_id' => 117, 'personnel_id' => 55,  'assignment_date' => '2019-01-03', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 101, 'plantilla_position_id' => 118, 'personnel_id' => 56,  'assignment_date' => '2019-07-16', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 102, 'plantilla_position_id' => 119, 'personnel_id' => 57,  'assignment_date' => '2023-08-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 103, 'plantilla_position_id' => 120, 'personnel_id' => 58,  'assignment_date' => '2024-10-01', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 104, 'plantilla_position_id' => 121, 'personnel_id' => 59,  'assignment_date' => '2014-03-07', 'created_at' => $now, 'updated_at' => $now],
//             ['assignment_id' => 105, 'plantilla_position_id' => 122, 'personnel_id' => null, 'assignment_date' => null,         'created_at' => $now, 'updated_at' => $now],
//         ]);

//         DB::statement('ALTER TABLE plantilla_assignments AUTO_INCREMENT = 106;');
//     }
// }